spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

jwt:
  accessSecret: ${JWT_ACCESS_SECRET}
  refreshSecret: ${JWT_REFRESH_SECRET}
  accessExpirationMs: 900000
  refreshExpirationMs: 2592000000
  cookieSecure: true
  cookieSameSite: None

admin:
  login: ${ADMIN_LOGIN}
  password: ${ADMIN_PASSWORD}
  email: ${ADMIN_EMAIL}

cors:
  allowedOrigins:
    - ${CORS_ALLOWED_ORIGINS}

app:
  upload-dir: /app/uploads
