ALTER TABLE users ADD COLUMN status_new VARCHAR(50);

UPDATE users SET status_new = CASE status
    WHEN 0 THEN 'ACTIVE'
    WHEN 1 THEN 'INACTIVE'
    WHEN 2 THEN 'DELETED'
    WHEN 3 THEN 'PENDING_DELETION'
    ELSE 'ACTIVE'
END;

ALTER TABLE users DROP COLUMN status;
ALTER TABLE users RENAME COLUMN status_new TO status;
ALTER TABLE users ALTER COLUMN status SET NOT NULL;
